### ISSUE TITLE
Releases have been removed

### ISSUE THREAD

**Issue by TomHAnderson** [placetopay-org/emailage#1]
Hello,

My company has been using your excellent library at version 0.2.14 for some time.  Today we discovered that release has been removed from this repository.  The hash for that release is https://github.com/placetopay-org/emailage/tree/0b8be40475c4deca8f6dd5bf6d4c991a3346841a

For our own reasons, we don't want to either drop your library or upgrade at this time.  We're certainly on notice to upgrade now!  But in the mean time will you please restore the 0.2.14 release?

**Comment by TomHAnderson** [comment]
You can use the cached versions at packagist to restore the releases on this library.

**Comment by dnetix** [comment]
Sorry for the inconvenience, the releases has been restored, we are moving our packages to this organization.

**Comment by TomHAnderson** [comment]
Thanks.  We've got a team triaging this.  I see the tags right now but not the releases.

**Comment by dnetix** [comment]
Ok I just created the release for the version you need, that solves your issue?

**Comment by TomHAnderson** [comment]
```
- Downloading zircote/swagger-php (4.2.9)
  0/46 [>---------------------------]   0%    Failed to download placetopay/emailage from dist: The "https://api.github.com/repos/placetopay/emailage/zipball/0b8be40475c4deca8f6dd5bf6d4c991a3346841a" file could not be downloaded (HTTP/2 404 )
```

I suspect this path is provided by composer through packagist and that this is now a problem with packagist caching.

**Comment by TomHAnderson** [comment]
I may be wrong but I think you should delete all the releases from packagist (X on the right in the list on the right) then `update`

**Comment by dnetix** [comment]
Just tried that, can you check now?

**Comment by TomHAnderson** [comment]
I still see all the releases here: https://packagist.org/packages/placetopay/emailage
Still getting the same error

**Comment by dnetix** [comment]
Yes, i deleted all of them and then updated the repo and those were the ones that refreshed

**Comment by TomHAnderson** [comment]
You've fixed our problem.  The final piece was I was using the original composer.lock and that had the wrong hash for your package as it has changed.
